# MIoT06 - Actividad 1

Faustino Díaz Montero
David Ricardo Beltrán Lozada
Francisco José Vives Martorell

In [ ]:
# Instalar librería psycopg2
# Antes debes asegurarte que "../PostgreSQL/13/bin" está en PATH de tu pc, sino te dará error al instalar psycopg2
!echo $PATH
# Si está el directorio bin de PostgreSQL versión 13 en PATH de tu pc, ya puedes instalar psycopg2 desde terminal o desde aquí
# Versión de psycopg2 recomendada: 2.9.3
!pip install psycopg2

In [ ]:
# Se usa la librería psycopg2, para usar postgresql
import psycopg2

# NUBE

In [ ]:
# Se obtiene la URL de la base de datos de ElephantSQL,
# que tiene formato postgres://usuario:contrasenya@maquina:puerto/bbdd

# bbdd: el nombre de la base de datos, en este caso: ddddd
bbdd = 'tgctfdnb' #cambiar por tu bbdd
# Usuario: nombre de usuario de la base de datos, en este caso: uuuuu
usuario = 'tgctfdnb' #cambiar por tu usuario
# Contraseña: contraseña de la base de datos, en este caso: ppppp
contrasenya = 'tyN1unF64Un724x7AmPX46CzDLpBTCQN' #cambiar por tu contraseña
# Máquina: nombre de la máquina/host (el que aloja) la base de datos, en este caso: mmmmm
maquina = 'tyke.db.elephantsql.com'
# Puerto: puerto de la base de datos, en este caso: 5432 (puerto por defecto)
puerto = '5432'

In [ ]:
# Conectar a la base de datos
conexion = psycopg2.connect(dbname=bbdd,
                            user=usuario,
                            password=contrasenya,
                            host=maquina,
                            port=puerto
)

In [ ]:
# Abrir un cursor para poder realizar operaciones sobre la base de datos
cursor = conexion.cursor()

In [ ]:
# Creamos el esquema banco
cursor.execute("CREATE SCHEMA BANCO;")

In [ ]:
conexion.commit()

In [ ]:
#creamos la tabla personas
#cursor.execute("CREATE DOMAIN banco.""TIPO_DOC"" AS character varying(10) CHECK (VALUE IN ('NIF','NIE','PASAPORTE'));")
#cursor.execute("CREATE DOMAIN banco.""TIPO_PERSONA"" AS character varying(10) CHECK (VALUE IN ('FISICA','JURIDICA'));")
cursor.execute("CREATE TABLE IF NOT EXISTS banco.""PERSONAS"" \
( \
    ""NUM_PERSONA"" character varying(9) NOT NULL, \
    ""ENTIDAD""  character varying(4) NOT NULL, \
    ""TIPO_DOCUMENTO"" banco.""TIPO_DOC"" NOT NULL, \
    ""DOCUMENTO"" character varying(10) NOT NULL, \
    ""TIPO_PERSONA"" banco.""TIPO_PERSONA"" NOT NULL, \
    ""NOMBRE"" character varying(50) NOT NULL, \
    ""APELLIDO1"" character varying(50) NOT NULL, \
    ""APELLIDO2"" character varying(50), \
    ""FC_NACIMIENTO"" date NOT NULL, \
    ""PAIS_NACIMIENTO"" character varying(3) NOT NULL, \
    ""FC_ALTA_CLIENTE"" date NOT NULL, \
    ""FC_BAJA_CLIENT"" date, \
    CONSTRAINT PK_PERSONAS PRIMARY KEY (""NUM_PERSONA"", ""ENTIDAD"") \
);")
conexion.commit()

In [ ]:
# Creamos la tabla contratos
#cursor.execute("CREATE DOMAIN banco.""TIPO_CONT"" AS character varying(10) CHECK (VALUE IN ('CUENTAS','PASIVO','PRESTAMOS','TARJETAS'));")
#cursor.execute("CREATE DOMAIN banco.""TIPO_REL"" AS character varying(12) CHECK (VALUE IN ('TITULAR','AUTORIZADO','BENEFICIARIO','APODERADO'));")
cursor.execute("CREATE TABLE IF NOT EXISTS banco.""CONTRATOS"" \
( \
    ""ENTIDAD_PERSONA"" character varying(4) NOT NULL, \
    ""NUM_PERSONA"" character varying(9) NOT NULL, \
    ""ENTIDAD"" character varying(4) NOT NULL, \
    ""CENTRO"" character varying(4) NOT NULL, \
    ""CUENTA"" character varying(10) NOT NULL, \
    ""TIPO_CONTRATO"" banco.""TIPO_CONT"" NOT NULL, \
    ""FC_ALTA_CONTRATO"" date, \
    ""FC_BAJA_CONTRATO"" date, \
    ""FC_ALTA_RELACION"" date, \
    ""FC_BAJA_RELACION"" date, \
    ""TIPO_RELACION"" banco.""TIPO_REL"", \
    CONSTRAINT ""PK_CONTRATOS"" PRIMARY KEY (""ENTIDAD"",""CENTRO"",""CUENTA""), \
    CONSTRAINT ""FK_PERSONAS"" FOREIGN KEY (""NUM_PERSONA"", ""ENTIDAD_PERSONA"") \
            REFERENCES banco.PERSONAS (""NUM_PERSONA,ENTIDAD"") \
            ON DELETE CASCADE \
            ON UPDATE CASCADE \
);")
conexion.commit()

In [ ]:
# Creamos la tabla cuentas
#cursor.execute("CREATE DOMAIN banco.""TIPO"" AS character varying(10) CHECK (VALUE IN ('CORRIENTE','AHORRO','LIBRETA','CREDITO'));")
cursor.execute("CREATE TABLE IF NOT EXISTS banco.""CUENTAS"" \
( \
    ""ENTIDAD"" character varying(4) NOT NULL, \
    ""CENTRO"" character varying(4) NOT NULL, \
    ""CUENTA"" character varying(10) NOT NULL, \
    ""TIPO_CUENTA"" banco.""TIPO"" NOT NULL, \
    ""FC_ALTA_CONTRATO"" date NOT NULL, \
    ""FC_BAJA_CONTRATO"" date, \
    ""MONEDA"" character varying(3) NOT NULL, \
    ""NUM_INTERVINIENTES"" numeric(5), \
    CONSTRAINT ""PK_CUENTAS"" PRIMARY KEY (""ENTIDAD"",""CENTRO"", ""CUENTA""), \
    CONSTRAINT ""FK_CONTRATOS"" FOREIGN KEY (""ENTIDAD"", ""CENTRO"",""CUENTA"") \
        REFERENCES banco.""CONTRATOS"" (""ENTIDAD"", ""CENTRO"",""CUENTA"") \
        ON DELETE CASCADE \
        ON UPDATE CASCADE \
);")
conexion.commit()

In [ ]:
# Creamos la tabla pasivo
#cursor.execute("CREATE DOMAIN banco.""TIPO_PASIVO"" AS character varying(20) CHECK (VALUE IN ('PLAZO_FIJO','PIAS','PENSION'));")
cursor.execute("CREATE TABLE BANCO.PASIVO ( \
  ""ENTIDAD"" character varying(4) NOT NULL, \
  ""CENTRO"" character varying(4) NOT NULL, \
  ""CUENTA"" character varying(10) NOT NULL, \
  ""TIPO_CUENTA"" banco.""tipo_pasivo"" NOT NULL, \
  ""FC_ALTA_CONTRATO"" date NOT NULL, \
  ""FC_BAJA_CONTRATO"" date, \
  ""ENTIDAD_VINCULO"" character varying(4) NOT NULL, \
  ""CENTRO_VINCULO"" character varying(4) NOT NULL, \
  ""CUENTA_VINCULO"" character varying(10) NOT NULL, \
  CONSTRAINT ""PK_PASIVO"" PRIMARY KEY (""ENTIDAD"",""CENTRO"",""CUENTA""), \
  CONSTRAINT ""FK_CUENTAS"" FOREIGN KEY (""ENTIDAD_VINCULO"", ""CENTRO_VINCULO"",""CUENTA_VINCULO"") \
    REFERENCES BANCO.CUENTAS (""ENTIDAD"", ""CENTRO"",""CUENTA"") \
        ON DELETE CASCADE \
        ON UPDATE CASCADE \
);")
conexion.commit()

In [ ]:
#Creamos la tabla préstamos
#cursor.execute("CREATE DOMAIN banco.""TIPO_PTMO"" AS character varying(11) CHECK (VALUE IN ('HIPOTECARIO','PERSONAL','CONSUMO','LEASING','RENTING'));")
#cursor.execute("CREATE DOMAIN banco.""TIPO_GAR"" AS character varying(12) CHECK (VALUE IN ('INMOBILIARIA','FACIAL','AVAL','MOBILIARIA'));")
#cursor.execute("CREATE DOMAIN banco.""FORMA_INT"" AS character varying(12) CHECK (VALUE IN ('FIJO','VARIABLE','MIXTO'));")
cursor.execute("CREATE TABLE IF NOT EXISTS banco.""PRESTAMOS"" \
( \
    ""ENTIDAD"" character varying(4) NOT NULL, \
    ""CENTRO"" character varying(4) NOT NULL, \
    ""CUENTA"" character varying(10) NOT NULL, \
    ""TIPO_PRESTAMO"" banco.""TIPO_PTMO"" NOT NULL, \
    ""TIPO_GARANTIA"" banco.""TIPO_GAR"" NOT NULL, \
    ""FC_ALTA_CONTRATO"" date NOT NULL, \
    ""FC_BAJA_CONTRATO"" date, \
    ""FC_VENCIMIENTO"" date NOT NULL, \
    ""MONEDA"" character varying(3) NOT NULL, \
    ""CAPITAL_INICIAL"" numeric(12,2) NOT NULL, \
    ""CAPITAL_PENDIENTE"" numeric(12,2) NOT NULL, \
    ""FORMA_INTERES"" banco.""FORMA_INT"" NOT NULL, \
    ""ENTIDAD_VINCULO"" character varying(4) NOT NULL, \
    ""CENTRO_VINCULO"" character varying(4) NOT NULL, \
    ""CUENTA_VINCULO"" character varying(10) NOT NULL, \
    ""NUM_INTERVINIENTES"" integer, \
    CONSTRAINT ""PK_PRESTAMOS"" PRIMARY KEY (""ENTIDAD"",""CENTRO"",""CUENTA""), \
    CONSTRAINT FK_CUENTAS FOREIGN KEY (ENTIDAD_VINCULO, CENTRO_VINCULO,CUENTA_VINCULO) \
        REFERENCES banco.""CUENTAS"" (""ENTIDAD"", ""CENTRO"",""CUENTA"") \
            ON DELETE CASCADE \
            ON UPDATE CASCADE \
);")
conexion.commit()

In [ ]:
# Creamos la tabla tarjetas
#cursor.execute("CREATE DOMAIN banco.""TIPO_TJTA"" AS character varying(11) CHECK (VALUE IN ('DEBITO','CREDITO','MIXTA'));")
#cursor.execute("CREATE DOMAIN banco.""TIPO_PROD"" AS character varying(12) CHECK (VALUE IN ('VISA','MASTERCARD','AMERICAN EXPRESS','4B'));")
#cursor.execute("CREATE DOMAIN banco.""TIPO_BAJA"" AS character varying(12) CHECK (VALUE IN ('ROBO','EXTRAVIO','CADUCIDAD','IMPAGO'));")
#cursor.execute("CREATE DOMAIN banco.""TIPO_PAGO"" AS character varying(12) CHECK (VALUE IN ('INMEDIATO','MENSUAL','BIMENSUAL','PORCENTUAL'));")
#cursor.execute("CREATE DOMAIN banco.""STATUS"" AS character varying(12) CHECK (VALUE IN ('ACTIVA','BAJA','ESTAMPADA','CADUCADA','REVOCADA','BLOQUEADA'));")
cursor.execute("CREATE TABLE IF NOT EXISTS banco.""TARJETAS"" \
( \
    ""ENTIDAD"" character varying(4) NOT NULL, \
    ""CENTRO"" character varying(4) NOT NULL, \
    ""CUENTA"" character varying(10) NOT NULL, \
    ""NUM_TARJETA"" character varying(16) NOT NULL, \
    ""TIPO_TARJETA"" banco.""TIPO_TJTA"" NOT NULL, \
    ""TIPO_PRODUCTO"" banco.""TIPO_PROD"" NOT NULL, \
    ""FC_ALTA"" date NOT NULL, \
    ""FC_BAJA"" date, \
    ""MOTIVO_BAJA"" banco.""TIPO_BAJA"", \
    ""FORMA_PAGO"" banco.""TIPO_PAGO"", \
    ""PORCENTAJE_PAGO"" numeric(5,2), \
    ""FC_CADUCIDAD"" date NOT NULL, \
    ""FC_ESTAMPACION"" date NOT NULL, \
    ""ENTIDAD_VINCULO"" character varying(4) NOT NULL, \
    ""CENTRO_VINCULO"" character varying(4) NOT NULL, \
    ""CUENTA_VINCULO"" character varying(10) NOT NULL, \
    ""ESTADO"" banco.status, \
    CONSTRAINT ""PK_TARJETA"" PRIMARY KEY (""NUM_TARJETA""), \
    CONSTRAINT ""FK_CONTRATOS"" FOREIGN KEY (""ENTIDAD"", ""CENTRO"",""CUENTA"") \
        REFERENCES banco.""CONTRATOS"" (""ENTIDAD"", ""CENTRO"",""CUENTA"") \
            ON DELETE CASCADE \
            ON UPDATE CASCADE, \
    CONSTRAINT ""FK_CUENTAS"" FOREIGN KEY (""ENTIDAD_VINCULO"", ""CENTRO_VINCULO"",""CUENTA_VINCULO"") \
        REFERENCES banco.""CUENTAS"" (""ENTIDAD"", ""CENTRO"",""CUENTA"") \
            ON DELETE CASCADE \
            ON UPDATE CASCADE \
);")
conexion.commit()

In [ ]:
# Creamos la tabla de movimientos de cuentas
#cursor.execute("CREATE DOMAIN banco.""TIPO_MOVIM"" AS character varying(20) CHECK (VALUE IN ('INGRESO','REINTEGRO','TRANSFERENCIA','CHEQUE','MOV_CTA_VINCULO','GASTO','COMISION'));")
#cursor.execute("CREATE DOMAIN banco.""NATURALEZA"" AS character varying(5) CHECK (VALUE IN ('DEBE','HABER'));")
cursor.execute("CREATE TABLE IF NOT EXISTS banco.""MOVIMIENTOS_CUENTAS"" \
( \
    ""ENTIDAD"" character varying(4) NOT NULL, \
    ""CENTRO"" character varying(4) NOT NULL, \
    ""CUENTA"" character varying(10) NOT NULL, \
    ""FC_MOVIMIENTO"" date NOT NULL, \
    ""NUMERO_MOVIMIENTO"" numeric NOT NULL, \
    ""IMPORTE"" numeric(15,2) NOT NULL, \
    ""DEBE_HABER"" banco.""naturaleza"" NOT NULL, \
    ""TIPO_MOVIMIENTO"" banco.""TIPO_MOVIM"" NOT NULL, \
    ""CONCEPTO"" character varying(50) NOT NULL, \
    ""OBSERVACIONES"" character varying(50) NOT NULL, \
    ""MONEDA"" character varying(3) NOT NULL, \
    ""CENTRO_MOV"" character varying(4) NOT NULL, \
    ""REF_BENEFICIARIO"" character varying(50) NOT NULL, \
    ""REF_ORDENANTE"" character varying(50) NOT NULL, \
    CONSTRAINT ""PK_MOVIMIENTOS"" PRIMARY KEY (""ENTIDAD"",""CENTRO"",""CUENTA"",""FC_MOVIMIENTO"",""NUMERO_MOVIMIENTO""), \
    CONSTRAINT ""FK_CUENTAS"" FOREIGN KEY (""ENTIDAD"", ""CENTRO"",""CUENTA"") \
        REFERENCES banco.""CUENTAS"" (""ENTIDAD"", ""CENTRO"",""CUENTA"") \
            ON DELETE CASCADE \
            ON UPDATE CASCADE \
);")
conexion.commit()

In [ ]:
# Creamos la tabla de movimientos de pasivo
#cursor.execute("CREATE DOMAIN banco.""TIPO_PLAZO"" AS character varying(20) CHECK (VALUE IN ('IMPOSICION','REINTEGRO_TOTAL','REINTEGRO_PARCIAL'));")
#cursor.execute("CREATE DOMAIN banco.""TIEMPO"" AS character varying(20) CHECK (VALUE IN ('SEMANA','MES','ANYO'));")
cursor.execute("CREATE TABLE IF NOT EXISTS banco.""MOVIMIENTOS_PASIVO"" \
( \
    ""ENTIDAD"" character varying(4) NOT NULL, \
    ""CENTRO"" character varying(4) NOT NULL, \
    ""CUENTA"" character varying(10) NOT NULL, \
    ""FC_ALTA"" date NOT NULL, \
    ""FC_VENCIMIENTO"" date NOT NULL, \
    ""FC_CANCELACION"" date NOT NULL, \
    ""NUMERO_PLAZO"" numeric NOT NULL, \
    ""IMPORTE"" numeric (15,2) NOT NULL, \
    ""MONEDA"" character varying(3) NOT NULL, \
    ""TIPO_MOVIMIENTO"" banco.""TIPO_PLAZO"" NOT NULL, \
    ""PLAZO"" numeric(3) NOT NULL, \
    ""UNIDAD_TIEMPO"" banco.""TIEMPO"" NOT NULL, \
    ""TIPO_INTERES"" numeric(5,2) NOT NULL, \
    CONSTRAINT ""PK_MOV_PLAZO"" PRIMARY KEY (""ENTIDAD"",""CENTRO"",""CUENTA"",""NUMERO_PLAZO""), \
    CONSTRAINT ""FK_PASIVO FOREIGN"" KEY (""ENTIDAD"", ""CENTRO"",""CUENTA"") \
        REFERENCES banco.""PASIVO"" (""ENTIDAD"", ""CENTRO"",""CUENTA"") \
            ON DELETE CASCADE \
            ON UPDATE CASCADE \
);")
conexion.commit()

In [ ]:
# Creamos la tabla de movimientos de préstamos
#cursor.execute("CREATE DOMAIN banco.""TIPO_MOV_PTMO"" AS character varying(20) CHECK (VALUE IN ('CUOTA','APLAZADO','AMORTIZACION','COMISION','GASTOS'));")
cursor.execute("CREATE TABLE IF NOT EXISTS banco.""MOVIMIENTOS_PRESTAMOS"" \
( \
    ""ENTIDAD"" character varying(4) NOT NULL, \
    ""CENTRO"" character varying(4) NOT NULL, \
    ""CUENTA"" character varying(10) NOT NULL, \
    ""FC_CUOTA"" date NOT NULL, \
    ""NUMERO_MOVIMIENTO"" numeric NOT NULL, \
    ""TIPO_MOVIMIENTO"" banco.""TIPO_MOV_PTMO"" NOT NULL, \
    ""IMPORTE_MOVIMIENTO"" numeric(15,2) NOT NULL, \
    ""IMPORTE_CAPITAL"" numeric(15,2) NOT NULL, \
    ""IMPORTE_INTERESES"" numeric(15,2) NOT NULL, \
    ""IMPORTE_GASTOS"" numeric(15,2) NOT NULL, \
    ""CONCEPTO"" character varying(50) NOT NULL, \
    ""OBSERVACIONES"" character varying(50) NOT NULL, \
    ""MONEDA"" character varying(3) NOT NULL, \
    ""CENTRO_MOV"" character varying(4) NOT NULL, \
    ""REF_BENEFICIARIO"" character varying(50) NOT NULL, \
    ""REF_ORDENANTE"" character varying(50) NOT NULL, \
    CONSTRAINT ""PK_MVTOS_PTMOS"" PRIMARY KEY (""ENTIDAD"",""CENTRO"",""CUENTA"",""NUMERO_MOVIMIENTO""), \
    CONSTRAINT ""FK_CONTRATOS"" FOREIGN KEY (""ENTIDAD"",""CENTRO"",""CUENTA"") \
        REFERENCES banco.""PRESTAMOS"" (""ENTIDAD"",""CENTRO"",""CUENTA"") \
            ON DELETE CASCADE \
            ON UPDATE CASCADE \
);")
conexion.commit()

In [ ]:
# Creamos la tabla de movimientos de tarjetas
cursor.execute("CREATE TABLE IF NOT EXISTS banco.""MOVIMIENTOS_TARJETAS"" \
( \
    ""ENTIDAD"" character varying(4) NOT NULL, \
    ""CENTRO"" character varying(4) NOT NULL, \
    ""NUM_TARJETA"" character varying(16) NOT NULL, \
    ""NUM_EXTRACTO"" numeric NOT NULL, \
    ""NUM_MOVIMIENTO"" numeric NOT NULL, \
    ""FC_MOVIMIENTO"" date NOT NULL, \
    ""MONEDA"" character varying(3) NOT NULL, \
    ""CODIGO_COMERCIO"" character varying(9) NOT NULL, \
    ""IMPORTE"" numeric(15,2) NOT NULL, \
    ""IMPORTE_COMISION"" numeric(15,2) NOT NULL,  \
    ""CENTRO_MOVIMIENT"" character varying(4) NOT NULL, \
    CONSTRAINT ""PK_MVTOS_TJTAS"" PRIMARY KEY (""NUM_TARJETA"",""NUM_MOVIMIENTO""), \
    CONSTRAINT ""FK_TARJETAS"" FOREIGN KEY (""NUM_TARJETA"") \
        REFERENCES banco.""TARJETAS"" (""NUM_TARJETA"") \
            ON DELETE CASCADE \
            ON UPDATE CASCADE \
);")
conexion.commit()

In [ ]:
# Insert
cursor.execute("INSERT INTO banco.PERSONAS(NUM_PERSONA, ENTIDAD, TIPO_DOCUMENTO, DOCUMENTO, TIPO_PERSONA, NOMBRE, APELLIDO1, APELLIDO2, FC_NACIMIENTO, PAIS_NACIMIENTO, FC_ALTA_CLIENTE) \
                                    VALUES('000000001', '2001', 'NIF', '123456789A','FISICA', 'PEPA','GARCIA','PEREZ','01/01/2000','ESP','01/01/2005');")
conexion.commit()
cursor.execute("INSERT INTO banco.CONTRATOS(ENTIDAD_PERSONA, NUM_PERSONA, ENTIDAD, CENTRO, CUENTA, TIPO_CONTRATO, FC_ALTA_CONTRATO, FC_ALTA_RELACION, FC_BAJA_RELACION, TIPO_RELACION) \
                                    VALUES ('2001', '000000001', '2001', '0001', '5500000001', 'TARJETAS', '01/01/2005', '01/01/2005','10/10/2020', 'TITULAR');")
conexion.commit()
cursor.execute("INSERT INTO banco.CUENTAS(ENTIDAD, CENTRO, CUENTA, TIPO_CUENTA, FC_ALTA_CONTRATO, MONEDA, NUM_INTERVINIENTES) \
                                  VALUES ('2001', '0001', '3100000001', 'AHORRO', '01/01/2005', 'EUR', 1);")
conexion.commit()
cursor.execute("INSERT INTO banco.PASIVO(ENTIDAD, CENTRO, CUENTA, TIPO_CUENTA, FC_ALTA_CONTRATO, ENTIDAD_VINCULO, CENTRO_VINCULO, CUENTA_VINCULO) \ 
                                 VALUES ('2001', '0001', '5400000001', 'PLAZO_FIJO', '01/01/2005', '2001', '0001', '3100000001');")
conexion.commit()
cursor.execute("INSERT INTO banco.PRESTAMOS(ENTIDAD, CENTRO, CUENTA, TIPO_PRESTAMO, TIPO_GARANTIA, FC_ALTA_CONTRATO, FC_VENCIMIENTO, MONEDA, CAPITAL_INICIAL, CAPITAL_PENDIENTE, FORMA_INTERES, ENTIDAD_VINCULO, CENTRO_VINCULO, CUENTA_VINCULO, NUM_INTERVINIENTES) \
                                    VALUES ('2001', '0001', '5200000001','HIPOTECARIO', 'INMOBILIARIA', '01/01/2005', '01/01/2025','EUR', 200000, 125002.35, 'VARIABLE', '2001', '0001', '3100000001', 1);")
conexion.commit()
cursor.execute("INSERT INTO banco.TARJETAS(ENTIDAD, CENTRO, CUENTA, NUM_TARJETA, TIPO_TARJETA, TIPO_PRODUCTO, FC_ALTA, FORMA_PAGO, PORCENTAJE_PAGO, FC_CADUCIDAD, FC_ESTAMPACION, ENTIDAD_VINCULO, CENTRO_VINCULO, CUENTA_VINCULO, ESTADO) \
                                   VALUES ('2001', '0001', '5500000001', '4958000100020003', 'CREDITO','VISA', '01/01/2005','MENSUAL', 100, '01/01/2035', '01/01/2005', '2001', '0001', '3100000001', 'ACTIVA');")
conexion.commit()
cursor.execute("INSERT INTO banco.MOVIMIENTOS_CUENTAS(ENTIDAD, CENTRO, CUENTA, FC_MOVIMIENTO, NUMERO_MOVIMIENTO, IMPORTE, DEBE_HABER, TIPO_MOVIMIENTO, CONCEPTO, OBSERVACIONES, MONEDA, CENTRO_MOV, REF_BENEFICIARIO, REF_ORDENANTE) \
                                              VALUES ('2001', '0001', '3100000001', '01/01/2005', 1, 1500000, 'HABER', 'INGRESO', 'APERTURA CUENTA', 'NUEVO CLIENTE', 'EUR', '0001', 'INGRESO PROPIO', 'INGRESO PROPIO');")
conexion.commit()
cursor.execute("INSERT INTO banco.MOVIMIENTOS_PRESTAMOS(ENTIDAD, CENTRO, CUENTA, FC_CUOTA, NUMERO_MOVIMIENTO, TIPO_MOVIMIENTO, IMPORTE_MOVIMIENTO, IMPORTE_CAPITAL, IMPORTE_INTERESES, IMPORTE_GASTOS, CONCEPTO, OBSERVACIONES, MONEDA, CENTRO_MOV, REF_BENEFICIARIO, REF_ORDENANTE) \
                                                VALUES ('2001', '0001', '5200000001', '01/02/2005', 1, 'APLAZADO', 200000, 200000, 0, 0, 'APERTURA', 'PRESTAMO HIPOTECARIO','EUR', '2001', 'PRESTAMO HIPOTECARIO', 'PRESTAMO HIPOTECARIO');")
conexion.commit()
cursor.execute("INSERT INTO banco.MOVIMIENTOS_PASIVO(ENTIDAD, CENTRO, CUENTA, FC_ALTA, FC_VENCIMIENTO, FC_CANCELACION,NUMERO_PLAZO, IMPORTE, MONEDA, TIPO_MOVIMIENTO, PLAZO, UNIDAD_TIEMPO, TIPO_INTERES) \
                                             VALUES ('2001', '0001', '5400000001', '01/01/2005', '01/01/2025','01/01/2020',1, 100000, 'EUR', 'IMPOSICION', 20, 'ANYO', 5.25);")
conexion.commit()
cursor.execute("INSERT INTO banco.MOVIMIENTOS_TARJETAS(ENTIDAD, CENTRO, NUM_TARJETA, NUM_EXTRACTO, NUM_MOVIMIENTO, FC_MOVIMIENTO, MONEDA, CODIGO_COMERCIO, IMPORTE, IMPORTE_COMISION, CENTRO_MOVIMIENTO) \
                                               VALUES ('2001', '0001', '4958000100020003', 1, 1, '01/05/2005','EUR', '101010101', 150, 0.5, '0001');")
conexion.commit()

In [ ]:
# Select
# consulta de clientes
conexion.commit()
cursor.execute("SELECT * FROM banco.""PERSONAS"" where ""DOCUMENTO""='123456789A';")

In [ ]:
# Select
# consulta de clientes
cursor.execute("SELECT * FROM banco.PERSONAS where DOCUMENTO='123456789A';")
cursor.fetchall()
# contratos de un cliente
cursor.execute("select cont.*  \
                from banco.CONTRATOS cont, banco.PERSONAS per  \
                where per.NUM_PERSONA = cont.NUM_PERSONA and per.DOCUMENTO='123456789A';") 
cursor.fetchall()

# detalle de contratos de cuentas de un cliente
cursor.execute("select cuent.* \
                from banco.CONTRATOS cont, banco.PERSONAS per, banco.CUENTAS cuent \ 
                where per.NUM_PERSONA = cont.NUM_PERSONA and  \
                      cont.ENTIDAD = cuent.ENTIDAD and \
                      cont.CENTRO = cuent.CENTRO and  \
                      cont.CUENTA = cuent.CUENTA and \
                      per.DOCUMENTO='123456789A';")
cursor.fetchall()

# detalle de contratos de pasivo de un cliente
cursor.execute("select pas.*  \
                from banco.CONTRATOS cont, banco.PERSONAS per, banco.PASIVO pas  \
                where per.NUM_PERSONA = cont.NUM_PERSONA and \
                      cont.ENTIDAD = pas.ENTIDAD and \
                      cont.CENTRO = pas.CENTRO and \
                      cont.CUENTA = pas.CUENTA and \
                      per.DOCUMENTO='123456789A';")
cursor.fetchall()

# detalle de contratos de prestamos de un cliente
cursor.execute("select pres.* \ 
                from banco.CONTRATOS cont, banco.PERSONAS per, banco.PRESTAMOS pres \ 
                where per.NUM_PERSONA = cont.NUM_PERSONA and \
                      cont.ENTIDAD = pres.ENTIDAD and \
                      cont.CENTRO = pres.CENTRO and \
                      cont.CUENTA = pres.CUENTA and \
                      per.DOCUMENTO='123456789A';")
cursor.fetchall()

# detalle de contratos de tarjetas de un cliente
cursor.execute("select tjta.* \ 
                from banco.CONTRATOS cont, banco.PERSONAS per, banco.TARJETAS tjta \ 
                where per.NUM_PERSONA = cont.NUM_PERSONA and \
                      cont.ENTIDAD = tjta.ENTIDAD and \
                      cont.CENTRO = tjta.CENTRO and \
                      cont.CUENTA = tjta.CUENTA and \
                      per.DOCUMENTO='123456789A';
cursor.fetchall()
               
# detalle de los movimientos de las cuentas de un cliente
cursor.execute("select cuent.* \
                from banco.CONTRATOS cont, banco.PERSONAS per, banco.MOVIMIENTOS_CUENTAS cuent \ 
                where per.NUM_PERSONA = cont.NUM_PERSONA and \
                      cont.ENTIDAD = cuent.ENTIDAD and \
                      cont.CENTRO = cuent.CENTRO and \
                      cont.CUENTA = cuent.CUENTA and \
                      per.DOCUMENTO='123456789A';")
cursor.fetchall()
               
# detalle de los movimientos de pasivo de un cliente
cursor.execute("select pas.* \
                from banco.CONTRATOS cont, banco.PERSONAS per, banco.MOVIMIENTOS_PASIVO pas \ 
                where per.NUM_PERSONA = cont.NUM_PERSONA and \
                      cont.ENTIDAD = pas.ENTIDAD and \
                      cont.CENTRO = pas.CENTRO and \
                      cont.CUENTA = pas.CUENTA and \
                      per.DOCUMENTO='123456789A';")
cursor.fetchall()
               
# detalle de los movimientos de prestamos de un cliente
cursor.execute("select ptmo.* \
                from banco.CONTRATOS cont, banco.PERSONAS per, banco.MOVIMIENTOS_PRESTAMOS ptmo \ 
                where per.NUM_PERSONA = cont.NUM_PERSONA and \
                      cont.ENTIDAD = ptmo.ENTIDAD and \
                      cont.CENTRO = ptmo.CENTRO and \
                      cont.CUENTA = ptmo.CUENTA and \
                      per.DOCUMENTO='123456789A';")
cursor.fetchall()
               
# detalle de los movimientos de tarjetas de un cliente
cursor.execute("select mov_tjta.* \
                from banco.CONTRATOS cont, banco.PERSONAS per, \ 
                     banco.TARJETAS tjta, banco.MOVIMIENTOS_TARJETAS mov_tjta \ 
                where per.NUM_PERSONA = cont.NUM_PERSONA and \
                      cont.ENTIDAD = tjta.ENTIDAD and \
                      cont.CENTRO = tjta.CENTRO and \
                      cont.CUENTA = tjta.CUENTA and \
                      tjta.ENTIDAD = mov_tjta.ENTIDAD and \
                      tjta.NUM_TARJETA = mov_tjta.NUM_TARJETA and \
                      per.DOCUMENTO='123456789A';")
cursor.fetchall()

In [ ]:
# Cerrar el cursor
cursor.close()

In [ ]:
# Cerrar la conexión
conexion.close()